apiVersion: v1
kind: Namespace
metadata:
  name: creatures
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: creature-manager
  namespace: creatures
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: creature-manager
  namespace: creatures
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: creature-manager
  namespace: creatures
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: creature-manager
subjects:
  - kind: ServiceAccount
    name: creature-manager
    namespace: creatures
---
apiVersion: v1
kind: Secret
metadata:
  name: creature-manager-token
  namespace: creatures
  annotations:
    kubernetes.io/service-account.name: creature-manager
type: kubernetes.io/service-account-token
